config/routes.rb
Rails.application.routes.draw do

  resources :beers
  resources :my_beer_lists
  resources :notifications
  resources :patrons

  resources :users do
    resources :patrons
    resources :beers
    resources :notifications
  end

  resources :sessions, only: [:new, :create, :destroy]
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  root 'welcome#index'

  get 'users/:id/patron_list' => 'users#patron_list'
  get 'users/:id/beer_list' => 'users#beer_list'
  get 'users/:id/beer_list' => 'users#beer_list'
  get 'users/:id/notification_list' => 'users#notification_list'

end

app/models/user.rb
require "bcrypt"
class User < ActiveRecord::Base
	has_many :patrons
	has_many :beers
	has_many :notifications

	before_create :create_remember_token
	before_save { self.email = email.downcase }
	validates :bar_name, presence: true, length: { maximum: 100 }
	validates :username, presence: true, length: { maximum: 20 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,
  									format: { with: VALID_EMAIL_REGEX },
  									uniqueness: { case_sensitive: false },
  									confirmation: true
  has_secure_password
  validates :password, length: { minimum: 6 }

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.digest(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

    def create_remember_token
      self.remember_token = User.digest(User.new_remember_token)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :signed_in_user, only: [:edit, :update]
	before_action :correct_user, only: [:edit, :update]

	def index
		@users = User.all

	end

	def show
		@user = User.find(params[:id])
		@patrons = Patron.all
		patron_list
	end

	def patron_list
		@user = current_user
		@patrons = @user.patrons
		@patrons = @patrons.order("first_name ASC")
	end

	def beer_list
		@user = current_user
		@beers = @user.beers
		@beers = @beers.order("id DESC")	
	end

	def notification_list
		@user = current_user
		@notifications = @user.notifications
		@notifications = @notifications.order("id DESC")
		@beers = Beer.all
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			sign_in @user
			flash[:success] = "Welcome to Ale Mail!"
			redirect_to @user
		else
			render 'edit'
		end
	end

	def edit
	end

	def update
		if @user.update_attributes(user_params)
			flash[:success] = "Profile updated"
			redirect_to @user
		else
			render 'edit'
		end
	end

  private

		def user_params
			params.require(:user).permit(:bar_name, :username, :password, :password_confirmation, :phone, :address, :email)
		end

		# Before filters

		def signed_in_user
			unless signed_in?
				store_location
				redirect_to signin_url, notice: "Please sign in."
			end
		end

		def correct_user
			@user = User.find(params[:id])
			redirect_to(root_url) unless current_user?(@user)
		end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div class="my-fluid-container">
  <div class="col-xs-2">
  </div>
  <div class="col-xs-8">
    <div class="main-info-container">
      <div><%= bootstrap_form_for(@user) do |f| %><div>
        <div>  <%= f.text_field :bar_name  %></div>
        <div>  <%= f.text_field :username  %></div>
        <div>  <%= f.text_field :email %></div>
        <div>  <%= f.text_field :address %></div>
        <div>  <%= f.text_field :phone %></div>
        <div>  <%= f.password_field :password %></div>
        <div>  <%= f.password_field :password_confirmation %></div>
        <% if signed_in? %>
        <div>  <%= f.submit "Update info", class: "btn btn-large btn-primary" %></div>
        <% else %>
        <div>  <%= f.submit "Create my account", class: "btn btn-large btn-primary" %></div>
        <% end %>
        <% end %>
      </div>
      <div class="col-xs-2">
      </div>
      </div>
    </div>
  </div>
</div>

app/views/users/beer_list.html.erb
<div class="my-fluid-container">
	<div class="main-info-container large-info">
		<h1  class="past-note-heading">Beer List</h1>
		<%= link_to new_beer_path do %>
		<div class="beer-box box-font box-filler">Add New Beer</div>
		<% end %>
		<br />
		<% @beers.each do |b| %>
		<%= link_to edit_beer_path(b.id) do %>
		<div class="box-font">
			<div class="names beer-names"><%= b.name %> &nbsp; <span class='subcat'><%= b.style %><span></div>
		</div>
		<br />
		<% end %>
		<% end %>
	</div>
</div>
</div>

 

app/views/users/edit.html.erb
<%= render 'form' %>

app/views/users/index.html.erb
<h1><% @users.each do |u| %></h1>

			<%= u.bar_name %>
			<%= u.username %>
			<%= u.email %>

			<% end %>

app/views/users/notes.html.erb
<div class="row">
  <div class="span offset3">
    <%= form_for(@user) do |f| %>

      <%= f.label :bar_name %>
      <%= f.text_field :bar_name  %>

      <%= f.label :username %>
      <%= f.text_field :username  %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :address %>
      <%= f.text_field :address %>

      <%= f.label :phone %>
      <%= f.text_field :phone %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/notification_list.html.erb
<div class="main-info-container large-info">
	<div class="past-note-heading">Past Notifications</div>
	<div class="standard-text">
	<span>
		<div class="past-note-date">Date</div>
		<div class="past-note-beer">Beer</div>
		<div class="past-note-message">Message</div>
	</span>
	<br />
	<br />
		<% @notifications.each do |n| %>
			<div class="past-note-date"><%= n.created_at.strftime("%m/%d/%Y") %></div>
			<div class="past-note-beer"><%= @beers.find(n.beer_id).name %></div>
			<div class="past-note-message"><%= n.message_content %></div>
			<br />
			<br />
		<% end %>
	</div>
</div>

app/views/users/patron_list.html.erb
<div class="my-fluid-container">
	<div class="main-info-container medium-info">
		<h1 class="past-note-heading">List Of Fine Patrons</h1>
		<%= link_to new_patron_path do %>
		<div class="beer-box box-font box-filler">Add New Patron</div>
		<% end %>
		<br />
		<% @patrons.each do |p| %>
		<%= link_to edit_patron_path(p.id) do %>
		<div class=" box-font">
			<div class="names"><%= p.first_name %> &nbsp;<%= p.last_name %></div>
		</div>
		<br />
		<% end %>
		<% end %>
	</div>
</div>

app/views/users/show.html.erb
<div class="col-xs-12">
	<div class="custom-button">
		<%= link_to 'current_user/patrons/new' do %>
			<div class="active-button">
				<div class="icon-patron-new"></div>
				<div class="button-text">Create Patron</div>
			</div>
		<% end %>
	</div>
		
	<br />
	<div class="custom-button">
		<%= link_to 'current_user/notifications/new' do %>
			<div class="active-button">
				<div class="icon-notification"></div>
				<div class="button-text">Create Notification</div>
			</div>
		<% end %>
	</div>

	<div class="wide-buttons-space-break">

	<div class="custom-button dark-button">
		<%= link_to 'current_user/patron_list' do %>	
			<div class="active-button">
				<div class="icon-patron"></div>
				<div class="button-text">Find/Edit Patron</div>
			</div>
		<% end %>
	</div>
		<br />

		<div class="custom-button dark-button">
			<%= link_to 'current_user/beer_list' do %>
				<div class="active-button">
					<div class="icon-beer"></div>
					<div class="button-text">Add/Edit Beer</div>
				</div>
			<% end %>
			</div>
		<br />

		<div class="custom-button dark-button">
			<%= link_to 'current_user/notification_list' do %>
				<div class="active-button">
					<div class="icon-past-notification"></div>
					<div class="button-text">Past Notifications</div>
				</div>
			<% end %>		
			</div>
		<br />

	</div>

</div>