config/routes.rb
Rails.application.routes.draw do

  resources :beers
  resources :my_beer_lists
  resources :notifications
  resources :patrons

  resources :users do
    resources :patrons
    resources :beers
    resources :notifications
  end

  resources :sessions, only: [:new, :create, :destroy]
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  root 'welcome#index'

  get 'users/:id/patron_list' => 'users#patron_list'
  get 'users/:id/beer_list' => 'users#beer_list'
  get 'users/:id/beer_list' => 'users#beer_list'
  get 'users/:id/notification_list' => 'users#notification_list'

end

app/views/layouts/_footer.html.erb
<div class="fluid-container">
	<div class="footer-filler">
	</div>
</div>

app/views/layouts/_header.html.erb
<div class="fluid-container">
  <h1 id="header-title"><a href="#"></a>ALE MAIL</h1>
  <div class="navbar box-shadowed">
    <div class="nav-style">
      <% if signed_in? %>
        <%= link_to image_tag('/assets/home.png', :class => "home-img"), user_path(current_user) %>
      <div class="setting">
        <div class="nav nav pull-right settings-img">
            <div class= "dropdown-toggle" data-toggle="dropdown"><%= image_tag('/assets/settings.png', :class => "settings-img") %>
            </div>
              <ul class="dropdown-menu">              
                <li><%= link_to "Profile Settings", edit_user_path(current_user), :id => "setting-text" %></li>           
                <li><%= link_to "Sign out", signout_path, method: "delete", :id => "setting-text" %></li>
              </ul>
            </div>
      <% else %>
            <%= root_path %>
      <% end %>
        </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Alemailapp</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
  <link href='http://fonts.googleapis.com/css?family=Allan:400,700' rel='stylesheet' type='text/css'>
</head>
<body>
	<%= render 'layouts/header' %>
  <br />

  <div class="browser-size-message">
    <div class="custom-button">
      <div class="active-button">
        <div class="button-text"><h2 class"browser-size-text">This app is currently designed for use on standard-sized tablets. Please resize your browser or flip your device to portrait orientation</h2></div>
      </div>
    </div>
  </div>

    <div class="browser-size-message-small">
      <div class="custom-button">
        <div class="active-button">
          <div class="button-text"><h2 class"browser-size-text-small">This app is currently designed for use on standard-sized tablets. Please check back for the mobile version soon</h2></div>
        </div>
      </div>
    </div>

  	<div class="fluid-container">
  		<%= yield %>
  	</div>
    <%= render 'layouts/footer' %>
</body>
</html>